name: kinderguardian-tech
workers:
  - name: cron-worker
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: your-repo/kinderguardian
    envs:
      - key: CRON_SECRET_KEY
        scope: RUN_TIME
        value: "your-secret-key" 